//
//  NewsDataService.swift
//  WasteBank
//
//  Created by Putra Pebriano Nurba on 04/04/24.
//

import Foundation

class NewsDataService {
    static let instance: [NewsDataModel] = [
    NewsDataModel(
        cardTitle: "Penyerahan alat bantuan pengolahan sampah",
        informationCardTitle: "Bank sampah kelurahan purbayan tahun 2024",
        title: "Penyerahan bantuan alat-alat pengolahan sampah untuk bank sampah dan gerobak, Desa Purbayan",
        Image: URL(string: "https://purbayankel.jogjakota.go.id/assets/instansi/purbayankel/article/20240326101827.jpg"),
        contents: " Pada hari Jum'at, 15 Maret 2024, Kelurahan Purbayan Kemantren Kotagede mengadakan serangkaian acara penyerahan Bantuan Hibah Alat-alat Pengolahan Sampah untuk Bank Sampah dan Penggerobak Sampah di Kelurahan Purbayan. Kegiatan ini merupakan bentuk dukungan Pemerintah Kota Yogyakarta melalui Kelurahan Purbayan dalam membantu pengurus bank sampah dan penggerobak dalam menjalankan tugas dan peranannya dalam mengelola sampah di wilayah Kelurahan Purbayan. Kelurahan Purbayan mengapresiasi keberadaan Bank Sampah dan Shodaqoh Sampah di Wilayah Kelurahan Purbayan dalam peranannya mendukung program Pemerintah Kota Yogyakarta mengurangi dan memanfaatkan sampah rumah tangga menjadi barang yang berdaya guna dan bernilai. \n\n Acara penyerahan bantuan hibah Alat-alat Pengolahan Sampah untuk Bank Sampah dan Penggerobak sampah ini diikuti Bapak Mantri Pamong Praja Kotagede, Ibu Lurah Purbayan, Ketua LPMK Purbayan, Pengurus Faskel Bank Sampah, Tokoh-tokoh masyarakat di wilayah, perwakilan pengurus Bank Sampah, penggerobak sampah serta perangkat Kelurahan Purbayan. \n Dalam sambutannya, bapak Mantri Pamong Praja menyampaikan akan pentingnya kesadaran warga didukung oleh pemerintah untuk mengelola sampah warga secara mandiri baik organik maupun non organik dari hulunya dan hanya sampah yang residu yang dibuang di Tempat Pembuangan Sampah (TPS). Dalam sambutannya juga, Lurah Purbayan juga memotivasi bank sampah dan shodaqoh sampah yang ada di wilayah Kelurahan Purbayan untuk lebih berperan aktif di lingkungan masing-masing dalam mengelola sampah apalagi dengan dibantu peralatan bidang persampahan seperti gerobag sampah pilah, mesin pencacah sampah organik dan bin sampah pilah. \n\n Ketua LMPK Purbayan juga menyampaikan terima kasihnya kepada pemerintah Kota Yogyakarta atas bantuan hibah barang peralatan pengolahan persampahan kepada Pengurus Bank sampah dan penggerobak sampah, serta memotivasi bank sampah dan penggerobak sampah untuk lebih meningkatkan lagi peran sertanya dalam mengelola dan mengolah sampah dalam rangka mencapai target Kelurahan Purbayan bebas sampah tahun 2025. \n\n Semoga dengan bantuan tersebut banyak memberikan manfaat yang luas kepada masyarakat dan menjadikan kelurahan purbayan menjadi kelurahan yang bersih, sehat dan sejahtera"),
    NewsDataModel(
        cardTitle: "Bank sampah pulogadung Terbakar Hebat",
        informationCardTitle: "Diakibatkan sekelompok remaja bermain petasan",
        title: "Bank Sampah di Pulogadung Terbakar Dipicu Petasan, Belasan Mobil Pemadam Kebakaran Dikerahkan",
        Image: URL(string: "https://asset-2.tstatic.net/tribunnews/foto/bank/images/kebakaran12333.jpg"),
        contents: " Dipicu oleh bara petasan yang disulut anak-anak, bank sampah di area Terminal Pulogadung, Kelurahan/Kecamatan Pulogadung, Jakarta Timur terbakar pada Senin (25/3/2024) malam. \n\n Kasi Operasional Sudin Penanggulangan Kebakaran dan Penyelamatan Jakarta Timur, Gatot Sulaeman mengatakan, anak-anak di sekitar lokasi main petasan menyambar bank sampah, sehingga mengakibatkan timbul nyala api. \n\n Banyaknya tumpukan botol plastik dan kardus pada bank sampah luas 3×8 meter persegi itu, membuat api cepat membesar dalam waktu singkat. Sebanyak 11 unit mobil pompa berikut 45 personel Sudin Penanggulangan Kebakaran dan Penyelamatan Jakarta Timur dikerahkan guna memadamkan amuk si jago merah. \n\n Kerugian materil akibat terbakarnya bank sampah milik Terminal Pulogadung itu diperkirakan sebesar Rp3 juta rupiah. Guna mencegah kejadian serupa warga diimbau tidak bermain petasan, mengingat kasus kebakaran di Jakarta Timur akibat petasan ini bukan yang pertama kalinya."),
    NewsDataModel(
        cardTitle: "Dlh bandar lampung gandeng bank sampah",
        informationCardTitle: "Upaya pemkot lampung menanggulangi sampah",
        title: "Tangani persoalan sampah, Dlh bandar lampung gandeng 10 bank sampah",
        Image: URL(string: "https://www.rmollampung.id/uploads/images/2024/03/image_750x_65fed65f71f21.jpg"),
        contents: " Dinas Lingkungan Hidup (DLH) Kota Bandar Lampung menggandeng 10 bank sampah untuk menangani persoalan sampah di Kota Tapis Berseri.\n\n “Kita bekerjasama dengan 10 bank sampah yang ada di Unila, Kemiling, Panjang dan Sukabumi”, Kepala DLH Kota Bandar Lampung, Ahmad Husna, Sabtu (23/3).\n\n Menurutnya dengan adanya bank sampah ini dapat mengurangi volume sampah yang masuk ke TPA Bakung. Tak hanya itu, Ahmad Husna juga mengaku menggandeng peternak magot untuk mengelola sampah makanan. \n\n “Itu semua cukup membantu mengatasi permasalahan sampah,” jelasnya. \n\n Sebelumnya, Pemerintah Kota (Pemkot) Bandar Lampung melalui DLH menyebutkan terjadi peningkatan volume sampah saat bulan suci Ramadan 1445 Hijriah. \n\n “Selama Ramadan ini konsumsi makanan masyarakat meningkat, sehingga volume sampah juga mengalami peningkatkan sekitar 5 persen dari hari biasanya. Biasanya hanya 800 ton, jadi bertambah 20 sampai 25 ton,” ujarnya."),
    NewsDataModel(
        cardTitle: "TPST ngurah rai bali ditutup Pemerintah",
        informationCardTitle: "TPST ngurah rai bali kelebihan sampah",
        title: "TPST ngurah rai bali ditutup dikarenakan tidak mampu mengolah sampah kembali",
        Image: URL(string: "https://akcdn.detik.net.id/visual/2024/03/21/sampah-plastik-di-pantai-kedonganan-bali-4_169.jpeg?w=650&q=90"),
        contents: " Tempat pengolahan sampah terpadu (TPST) Tahura Ngurah Rai, Denpasar, Bali ditutup karena tidak mampu mengolah sampah. \n\n Wali Kota Denpasar I Gusti Ngurah Jaya Negara mengaku telah dipanggil pemerintah pusat terkait penutupan TPST Tahura Ngurah Rai.\n\n Tinggal yang di (TPST Kesiman) Kertalangu kalau juga tidak maksimal akan kami ganti dan tutup sesuai dengan ketentuan yang berlaku, ujar Jaya Negara  di Gedung Dharma Negara Alaya, Denpasar, Bali, Kamis (21/3).\n\n Menurut Jaya Negara, hasil pengolahan sampah dari TPST Kesiman berupa briket kurang laku. Pemkot Denpasar kesulitan mendapatkan pembeli briket hasil olah sampah tersebut. \n\n Belakangan, TPST Kesiman justru didemo karena mengeluarkan bau busuk. Jaya Negara berharap ada yang mau bekerja sama sehingga briket dari TPST Kesiman bisa terserap. Mudah-mudahan dengan adanya beberapa pihak yang mau bekerja sama dapat menjadi solusi baru, ungkap politikus PDIP tersebut. \n\n Saat ditanya apakah  TPST Tahura Ngurah Rai bakal ditutup permanen, Jaya Negara menjawab itu akan tutup permanen dengan sendirinya. Sebab, kata dia, sudah tidak bisa menampung volume sampah. \n\n TPST Kesiman dan TPST Tahura ditargetkan dapat mengolah sampah sebanyak 450 ton per hari. Adapun, TPST Padangsambian bisa mengolah sampah 120 ton per hari.\n\n Adapun alasan TSPT ditutup dikarenakan lahan yang menjadi Bank Sampah akan dialih fungsikan menjadi puskesmas. Kerena lokasinya yang strategis dan berdekatan dengan fasilitas umum seperti sekolah. \n\n Wali Kota Denpasar berharap dengan ditutupnya TPST akam membuat warga menjadi sadar dan membuat lingkungan menjadi bersih serta menjadi terkontrol."),
    NewsDataModel(
        cardTitle: "Kota Jayapura timbulkan sampah 241 ton",
        informationCardTitle: "Kota Jayapura Timbulkan sampah berton-ton",
        title: "DLHK Jayapura Sebut Jayapura Timbulkan Sampah Sebanyak 241 ton setiap hari",
        Image: URL(string: "https://img.antaranews.com/cache/800x533/2024/03/28/IMG20240328151154.jpg.webp"),
        contents: " Dinas Lingkungan Hidup dan Kebersihan (DLHK) Kota Jayapura, Papua menyebut timbulan sampah di daerah itu berdasarkan kebijakan dan strategi daerah pengelolaan sampah rumah tangga dan sampah sejenis sampah rumah tangga (Jakstrada) pada 2023 periode ke dua mencapai 241 ton per hari.\n\n Kepala Seksi Penanganan Pengurangan Sampah dan Limbah B3 DLHK Kota Jayapura Andry Kambu di Jayapura, Kamis, mengatakan dari total timbulan sampah tersebut yang di bawa ke Tempat Pembuangan Akhir (TPA) 190 ton per hari.\n\n Ada selisih sekitar 50 ton sampah, namun dari jumlah itu yang kami tangani sekitar lima ton per hari sehingga masih ada 45 ton sampah yang masih tertimbun di berbagai lokasi katanya.\n\n Menurutnya, untuk menangani 45 ton sampah tersebut maka diperlukan kerja lebih ekstra dari petugas di lapangan untuk membersihkan sisa sampah yang dihasilkan oleh masyarakat.\n\n Karena lingkungan yang kotor akan sangat berpengaruh terhadap penyakit seperti demam berdarah (DBD), ujarnya.\n\n Dia menjelaskan lingkungan yang bersih akan menurunkan populasi nyamuk dengan demikian penyakit menular seperti DBD bisa teratasi.\n\n Langkah kongkret yang akan kami ambil untuk menciptakan lingkungan yang bersih ialah membersihkan daerah yang berpotensi kotor atau saluran air tersumbat itu yang akan dibersihkan bekerjasama dengan RT/RW, katanya.\n\nDia menambahkan dengan demikian diharapkan tindakan itu akan mencegah pertumbuhan ataupun penyebaran penyakit DBD di Kota Jayapura.")
    ]
}
